/* Check the engine's word-level readings against Pritchett's glossary (data/glossary.json,
   387 entries with her syllable division and weights), and write glossary_lexicon.json:
   the entries whose scansion the general rules cannot produce, as lexical alternates.

   node glossary_check.js            -> results/glossary_check.json + glossary_lexicon.json
   Agreement is measured BEFORE the generated lexicon is applied (engine loaded with
   GLOSSARY=off), so the number reports how much of the glossary the rules alone explain. */
'use strict';
process.env.GLOSSARY_LEXICON = 'off';
const fs = require('fs'), path = require('path');
const E = require('./engine.js');
const A = require('./lib/ascii.js');
const GL = require('../data/glossary.json');

/* a glossary weight list like "(= - x), (= x)" -> ['l s x', 'l x'] */
const parsePats = wt => (wt.match(/\(([^)]*)\)/g) || []).map(p => p.slice(1, -1).trim().split(/\s+/).map(c => c === '=' ? 'l' : c === '-' ? 's' : 'x').join(' '));
/* engine pattern covers glossary pattern if lengths match and each position is compatible:
   glossary x needs engine x; glossary = / - accepts engine x (a flexible can be used either way) */
const covers = (eng, gl) => { const a = eng.split(' '), b = gl.split(' '); if(a.length !== b.length) return false;
  return a.every((e, k) => b[k] === 'x' ? e === 'x' : (e === b[k] || e === 'x')); };
/* a final one-letter short in the glossary may be written as a cheat (-) in a phrase: allow exact only */

function readingsForPhrase(ascii){
  const { words } = E.asciiWords(ascii);
  if(!words.length) return [];
  const units = E.buildUnits(words);
  /* enumerate full-phrase readings: concatenations of unit readings covering all words */
  const out = [];
  const go = (i, acc) => {
    if(out.length > 400) return;
    if(i === words.length){ out.push(acc.join(' ')); return; }
    for(const u of units[i]) for(const r of u.readings) go(u.to + 1, acc.concat(r.syl.map(s => s.w)));
  };
  go(0, []);
  return [...new Set(out)];
}

const report = [], lexicon = {};
let n = 0, ok = 0, partial = 0;
for(const g of GL){
  const pats = parsePats(g.wt);
  if(!pats.length) continue;
  n++;
  const eng = readingsForPhrase(g.ascii);
  const hit = pats.map(p => eng.some(e => covers(e, p)));
  const all = hit.every(Boolean), any = hit.some(Boolean);
  if(all) ok++; else if(any) partial++;
  report.push({ ascii: g.ascii, syl: g.syl, glossary: pats, engine: eng.slice(0, 8), covered: hit, mean: g.mean });
  /* single words the rules cannot produce -> lexical alternates, cited to the glossary */
  if(!all && !/\s/.test(g.ascii.trim())){
    const key = g.ascii.trim();
    lexicon[key] = lexicon[key] || [];
    pats.forEach((p, k) => { if(!hit[k]) lexicon[key].push({ pattern: p.split(' ').map(c => c === 'l' ? '=' : c === 's' ? '-' : 'x').join(' '), split: g.syl, rule:'G-glossary', opt:'alt', mean: g.mean }); });
  }
}
/* glossary lines that give two spellings for one ascii (bahut / bah-ut) are already covered by
   the same loop, since both rows share the ascii key */
const summary = { entries:n, all_patterns_covered:ok, partly_covered:partial, not_covered:n - ok - partial, pct_all:+(100 * ok / n).toFixed(1) };
fs.mkdirSync(path.join(__dirname, 'results'), { recursive:true });
fs.writeFileSync(path.join(__dirname, 'results', 'glossary_check.json'), JSON.stringify({ summary, report }, null, 1));
fs.writeFileSync(path.join(__dirname, 'glossary_lexicon.json'), JSON.stringify({ _about:'Generated by glossary_check.js from data/glossary.json: single-word glossary scansions the general rules do not produce. Loaded by lib/prosody.js as alternates under rule G-glossary.', words: lexicon }, null, 1));
console.log(summary);
if(process.argv.includes('-v')) report.filter(r => !r.covered.every(Boolean)).forEach(r => console.log(r.ascii.padEnd(24), r.syl.padEnd(22), JSON.stringify(r.glossary), '| engine:', JSON.stringify(r.engine.slice(0, 4)), '|', r.mean));
