/* Prosody layer: item strings -> syllable readings, every decision tagged with a rule id
   from rules.json. Nothing here knows about meters; lib/meter.js does the matching.

   A READING is { syl:[Syl], dec:[{id,opt,key}], cost } where each Syl is
     { w:'l'|'s'|'x', text, flex:{id,key,word}|null, cheat:bool, n:letters, iz, conj }
   'x' = flexible (1.5); its P(short) comes from params via flex.id/key/word.
   dec lists the choice rules applied (including the default option), so the learner
   can count opportunities as well as firings. */
'use strict';
const LEX = require('../lexicon.json');
const fs = require('fs'), path = require('path');
/* glossary-derived irregular words (generated by glossary_check.js); off while that script measures the rules alone */
const GLEX = (() => { if(process.env.GLOSSARY_LEXICON === 'off') return {};
  try { return JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'glossary_lexicon.json'), 'utf8')).words; } catch(e){ return {}; } })();
let DISABLED = new Set();
function disable(ids){ DISABLED = new Set(ids || []); }

const LONGV = new Set(['aa','ii','uu','e','o','ai','au']);
const VAO = new Set(['o','uu','au']), YE = new Set(['ii','e','ai']);

/* ---------- items -> letters (1.2: only letters count) ---------- */
function toLetters(items){
  const L = [];
  for(const it of items){
    if(it.k === 'v'){ const p = L[L.length-1]; if(p && (p.k === 'C')) p.v = it.s; else if(p && p.k === 'A') p.v = p.v || it.s; continue; }
    if(it.k === 'N'){ const p = L[L.length-1]; if(p) p.nas = true; continue; }
    if(it.k === 'H'){ const p = L[L.length-1]; if(p) p.asp = true; continue; }
    L.push(Object.assign({}, it));
  }
  return L;
}
const isV = x => x && x.k === 'V';
const isC = x => x && x.k === 'C';

/* ---------- regular syllabification: 1.2 (one or two letters), 1.3 (consonant onset
   wherever possible; vowel-initial only word-initially), 1.4 (follow pronunciation --
   the ASCII's short vowels say where the breaks are), 1.3 (hamza never 2nd letter) ---------- */
function syllabify(L){
  const syl = [];
  let i = 0;
  const canClose = j => { const c = L[j]; return isC(c) && !c.v && c.s !== '))' && !isV(L[j+1]) && !c.iz && !c.conj; };
  while(i < L.length){
    const x = L[i];
    if(x.k === 'AA'){ syl.push({L:[x], w:'l', kind:'AA'}); i++; continue; }
    if(x.k === 'A'){
      if(!x.v && isV(L[i+1])){ syl.push({L:[x, L[i+1]], w:'l', kind:'AV'}); i += 2; continue; }
      if(canClose(i+1)){ syl.push({L:[x, L[i+1]], w:'l', kind:'AC'}); i += 2; continue; }
      syl.push({L:[x], w:'s', kind:'A'}); i++; continue;
    }
    if(x.k === 'V'){ syl.push({L:[x], w: x.iz || x.conj ? 'x' : 'l', kind:'V'}); i++; continue; }  /* medial all-vowel (1.3 exception) */
    if(isV(L[i+1]) && !x.v){ syl.push({L:[x, L[i+1]], w:'l', kind:'CV'}); i += 2; continue; }
    if(x.v && canClose(i+1)){ syl.push({L:[x, L[i+1]], w:'l', kind: L[i+1].s === 'h' && i+2 === L.length ? 'CH' : 'CC'}); i += 2; continue; }
    syl.push({L:[x], w:'s', kind: x.v ? 'Cv' : 'C0'}); i++;
  }
  return syl;
}

function letterText(x){
  if(x.k === 'AA') return 'aa' + (x.nas ? ';N' : '');
  if(x.k === 'A') return (x.v || '') + (x.nas ? ';N' : '');
  if(x.k === 'V') return (x.iz ? '-' : x.conj ? '-' : '') + x.s + (x.nas ? ';N' : '');
  return x.s + (x.asp ? 'h' : '') + (x.v || '') + (x.nas ? ';N' : '');
}
const sylText = s => s.L.map(letterText).join('');

/* ---------- params access (set by engine) ---------- */
let P = null;
function setParams(p){ P = p; }
const cost = p => p <= 0 ? Infinity : -Math.log(p);

/* ---------- item-level alternatives ---------- */
function clone(items){ return items.map(x => Object.assign({}, x)); }
function lastLetterIdx(items){ for(let j = items.length-1; j >= 0; j--) if(!['v','N','H'].includes(items[j].k)) return j; return -1; }
function syllableCountRegular(items){ return syllabify(toLetters(items)).length; }

/* suffix (iẓāfat 3.2, o 3.3, al 3.4) applied to one item string -> [{items, dec}] */
function applySuffix(items, kind, ctx){
  const out = [];
  const j = lastLetterIdx(items); if(j < 0) return [{items, dec:[]}];
  const last = items[j];
  const tail = items.slice(j+1);          /* trailing v / N / H after the last letter */
  const hasShortV = tail.some(t => t.k === 'v');
  const suf = kind === 'iz' ? 'e' : 'o';
  const flag = kind === 'iz' ? {iz:true} : {conj:true};
  const R = kind === 'iz' ? 'F3.2' : 'F3.3';
  const push = (its, dec) => out.push({items:its, dec});
  const withSuf = (its, extra) => its.concat([Object.assign({k:'V', s:suf}, flag, extra||{})]);

  if(kind === 'al'){
    if(last.k === 'C' || last.k === 'A'){
      push(items.concat([{k:'v', s:'u'}, {k:'C', s:'l', art:true}]), [{id:'F3.4-al-consonant', opt:'join'}]);
    } else {
      /* vowel-final + al: the vowel is shortened (bi+al = bil, fii al-haal = fil-haal) */
      const its = items.slice(0, j).concat([{k:'v', s:'i'}, {k:'C', s:'l', art:true}]);
      push(its, [{id:'F3.4-al-vowel', opt:'shorten'}]);
    }
    return out;
  }

  if(last.k === 'C' && hasShortV && toLetters(items).length === 1){
    /* the transcription writes a one-consonant word with its short vowel (dar-pa-e): that
       consonant is already a syllable, so the suffix stands alone. (In sham((a-e the a is
       the ((ain's own vowel and the iẓāfat joins it as usual.) */
    push(withSuf(items, {alone:true, afterLong:'v'}), [{id: R + '-after-short-vowel', opt:'separate'}]);
    return out;
  }
  if(last.k === 'C'){
    /* 3.2 / 3.3 on a consonant: the suffix joins the last letter as a flexible syllable.
       A word-final gol he after a short vowel (siinah, jalvah) behaves as a consonant too. */
    const hFinal = last.s === 'h' && items[j-1] && items[j-1].k === 'v';
    const base = items.slice(0, j+1).concat(tail.filter(t => t.k !== 'v'));
    const key = hFinal ? 'h' : 'C';
    push(withSuf(base), [{id: R + '-consonant', opt:'join', key}]);
    if(hFinal && kind === 'o'){
      /* 3.3: "sometimes the h is pronounced and scanned as a vowel; the o forms an independent flexible syllable" */
      push(withSuf(items, {alone:true, afterLong:'h'}), [{id:'F3.3-o-h', opt:'vowel-h'}]);
      out[0].dec.push({id:'F3.3-o-h', opt:'consonant-h'});
    }
    /* Arabic two-consonant monosyllables: optional tashdīd on the final consonant (3.2, 3.3) */
    const Ls = toLetters(items);
    if(!hFinal && Ls.length === 2 && isC(Ls[0]) && Ls[0].v && isC(Ls[1]) && !Ls[1].v){
      const dup = Object.assign({}, last);
      out[0].dec.push({id: R + '-cc-tashdid', opt:'none', key: ctx.origin});
      push(withSuf(base.concat([dup])), [{id: R + '-cc-tashdid', opt:'tashdid', key: ctx.origin}]);
    }
    return out;
  }
  if(last.k === 'AA' || (last.k === 'V' && last.s === 'aa')){
    push(withSuf(items, {alone:true, afterLong:'aa'}), [{id: R + '-alif', opt:'separate'}]);
    if(last.dagger && kind === 'iz'){
      /* 4.4: a final dagger-alif on ye before an iẓāfat is sometimes scanned as ii (da((v;aa-e = da((-va-ye) */
      out[0].dec.push({id:'F4.4-dagger-izafat', opt:'as-alif'});
      push(withSuf(items.slice(0, j).concat([{k:'v', s:'a'}, {k:'C', s:'y'}])), [{id:'F4.4-dagger-izafat', opt:'as-ii'}]);
    }
    return out;
  }
  if(last.k === 'V' && VAO.has(last.s)){
    const asCons = items.slice(0, j).concat([{k:'v', s: last.s === 'au' ? 'a' : 'u'}, {k:'C', s:'v'}]);
    if(kind === 'iz'){
      const key = last.s === 'au' ? 'au' : 'o';
      push(withSuf(items, {alone:true, afterLong:'o'}), [{id:'F3.2-iz-vao', opt:'separate', key}]);
      push(withSuf(asCons), [{id:'F3.2-iz-vao', opt:'consonant', key}]);
    } else {
      push(withSuf(asCons), [{id:'F3.3-o-vowel', opt:'consonant', key:last.s}]);
      push(withSuf(items, {alone:true, afterLong:'o'}), [{id:'F3.3-o-vowel', opt:'separate', key:last.s}]);
    }
    return out;
  }
  if(last.k === 'V' && last.s === 'ii'){
    const asCons = items.slice(0, j).concat([{k:'v', s:'i'}, {k:'C', s:'y'}]);
    if(kind === 'iz'){
      push(withSuf(asCons), [{id:'F3.2-iz-ii', opt:'consonant'}]);
      push(withSuf(items, {alone:true, afterLong:'ii'}), [{id:'F3.2-iz-ii', opt:'separate'}]);
    } else {
      push(withSuf(items, {alone:true, afterLong:'ii'}), [{id:'F3.3-o-ii', opt:'separate'}]);
      push(withSuf(asCons), [{id:'F3.3-o-ii', opt:'consonant'}]);
    }
    return out;
  }
  if(last.k === 'V' && (last.s === 'e' || last.s === 'ai')){
    const asCons = items.slice(0, j).concat([{k:'v', s:'a'}, {k:'C', s:'y'}]);
    if(kind === 'iz') push(withSuf(asCons), [{id:'F3.2-iz-e', opt:'consonant'}]);
    else {
      push(withSuf(asCons), [{id:'F3.3-o-vowel', opt:'consonant', key:last.s}]);
      push(withSuf(items, {alone:true, afterLong:'e'}), [{id:'F3.3-o-vowel', opt:'separate', key:last.s}]);
    }
    return out;
  }
  /* A alone or anything else: attach as a separate syllable */
  push(withSuf(items, {alone:true}), [{id: R + '-other', opt:'separate'}]);
  return out;
}

/* ---------- lexicon-driven item alternatives (4.3 mh pronouns, 2.4 optional tashdīd) ---------- */
function lexicalItemAlts(word, items){
  const alts = [{items, dec:[]}];
  /* 4.3: the perfect forms of honaa are scanned as pronounced, hu))aa (- x), however spelled */
  if(!DISABLED.has('F4.3-huaa') && /^huu\)\)(aa|e|ii|ii;N|e;N)$/.test(word)){
    const k = items.findIndex(x => x.k === 'V' && x.s === 'uu');
    if(k > 0){ const its = clone(items); its[k] = {k:'v', s:'u'}; alts[0] = {items:its, dec:[{id:'F4.3-huaa', opt:'as-pronounced'}]}; }
  }
  /* 4.4: word-final hamza after alif is almost never scanned */
  { const n = items.length;
    if(!DISABLED.has('F4.4-final-hamza') && n >= 2 && items[n-1].k === 'C' && items[n-1].s === '))' && (items[n-2].k === 'V' && items[n-2].s === 'aa' || items[n-2].k === 'AA')){
      const a0 = alts[0];
      alts.length = 0;
      alts.push({items:a0.items.slice(0, -1), dec:a0.dec.concat([{id:'F4.4-final-hamza', opt:'silent'}])});
      alts.push({items:a0.items, dec:a0.dec.concat([{id:'F4.4-final-hamza', opt:'short'}])});
    } }
  /* 1.3 / 7: the amphibious ii -- a final ii straight after ((ain or hamza that closes a short
     syllable (sa((ii) may be the consonant y, a one-letter short */
  { const n = items.length;
    if(!DISABLED.has('F1.3-amphibious-ii') && n >= 3 && items[n-1].k === 'V' && items[n-1].s === 'ii' && items[n-2].k === 'C' && (items[n-2].s === '((' || items[n-2].s === '))') && items[n-3].k === 'v'){
      const base = alts.slice();
      base.forEach(a => { a.dec = a.dec.concat([{id:'F1.3-amphibious-ii', opt:'vowel'}]); alts.push({items:a.items.slice(0, -1).concat([{k:'C', s:'y'}]), dec:a.dec.slice(0, -1).concat([{id:'F1.3-amphibious-ii', opt:'consonant'}])}); });
    } }
  /* 1.2 / 7 (ASCII): n written after a long vowel before a consonant may stand for ;N */
  { const k = items.findIndex((x, j) => j > 0 && j < items.length-1 && x.k === 'C' && x.s === 'n' && (items[j-1].k === 'V' || items[j-1].k === 'AA') && items[j+1].k === 'C');
    if(!DISABLED.has('T-ascii-n-nasal') && k > 0){
      const base = alts.slice();
      base.forEach(a => { const kk = a.items.findIndex((x, j) => j > 0 && j < a.items.length-1 && x.k === 'C' && x.s === 'n' && (a.items[j-1].k === 'V' || a.items[j-1].k === 'AA') && a.items[j+1].k === 'C');
        if(kk < 0) return;
        const its = clone(a.items); its[kk] = {k:'N'};
        a.dec = a.dec.concat([{id:'T-ascii-n-nasal', opt:'as-written'}]);
        alts.push({items:its, dec:a.dec.slice(0, -1).concat([{id:'T-ascii-n-nasal', opt:'nasal'}])}); });
    } }
  /* 4.3: tumhaaraa, tumhe;N, unho;N...: the gol he is read as an aspirator */
  if(LEX.mh_pronouns.includes(word)){
    const j = items.findIndex((x, k) => x.k === 'C' && x.s === 'h' && k > 0 && items[k-1].k === 'C' && ['m','n','l'].includes(items[k-1].s));
    if(j > 0){
      const asp = clone(items); asp[j] = {k:'H'};
      alts.length = 0;
      alts.push({items:asp, dec:[{id:'F4.3-mh-pronoun', opt:'aspirate'}]});
      alts.push({items, dec:[{id:'F4.3-mh-pronoun', opt:'written'}]});
    }
  }
  /* Glossary p'hu;N-chaa (= x): in pahu;Nch- the written u is not scanned (the Urdu spelling پہنچ has none) */
  if(!DISABLED.has('G-pahunch') && /^pahu;Nch/.test(word)){
    const k = items.findIndex((x, j) => x.k === 'v' && x.s === 'u' && j > 0 && items[j-1].k === 'C' && items[j-1].s === 'h');
    if(k > 0){
      const base = alts.slice(); alts.length = 0;
      base.forEach(a => { alts.push({items:a.items, dec:a.dec.concat([{id:'G-pahunch', opt:'regular'}])});
        alts.push({items:a.items.filter((x, j) => j !== k), dec:a.dec.concat([{id:'G-pahunch', opt:'contracted'}])}); });
    }
  }
  /* 2.1 aur as one syllable, also when grafted onto the word before it (dard aur = dar-daur) */
  if(/_aur$/.test(word) && items.length && items[items.length-1].s === 'r'){
    const base = alts.slice(); alts.length = 0;
    base.forEach(a => { alts.push({items:a.items, dec:a.dec.concat([{id:'F2.1-aur', opt:'regular', key:'grafted'}])});
      alts.push({items:a.items.slice(0, -1), dec:a.dec.concat([{id:'F2.1-aur', opt:'alt', key:'grafted'}]), aurSingle:true}); });
  }
  /* 2.4 optional tashdīd in perfect forms (rakhaa, u;Thaa, likhaa...) */
  for(const t of LEX.optional_tashdid){
    const m = word.match(new RegExp('^' + t.re + '$'));
    if(!m) continue;
    const next = [];
    for(const a of alts){
      const its = a.items;
      /* double the first consonant that follows the first short vowel */
      const vi = its.findIndex(x => x.k === 'v' || x.k === 'A');
      const ci = its.findIndex((x, k) => k > vi && x.k === 'C');
      if(ci < 0){ next.push(a); continue; }
      const dbl = its.slice(0, ci).concat([Object.assign({}, its[ci])], its.slice(ci));
      next.push({items:its, dec:a.dec.concat([{id:'F2.4-optional-tashdid', opt:'absent', key:t.level}])});
      next.push({items:dbl, dec:a.dec.concat([{id:'F2.4-optional-tashdid', opt:'present', key:t.level}])});
    }
    alts.length = 0; next.forEach(x => alts.push(x));
  }
  return alts;
}

/* ---------- syllable-level alternatives (4.2 clusters, 4.3 conjuncts) ---------- */
function clusterAlts(syl, suffixed){
  const out = [{syl, dec:[]}];
  const n = syl.length;
  /* 4.2: consonant + long vowel + two consonants, word-final: (= -), never (= =) */
  if(!suffixed && n >= 3){
    const a = syl[n-3], b = syl[n-2], c = syl[n-1];
    const longEnd = a.L.length === 2 && (isV(a.L[1]) && LONGV.has(a.L[1].s)) || (a.kind === 'AA');
    if(longEnd && b.kind === 'C0' && c.kind === 'C0' && b.L[0].s !== '))' && c.L[0].s !== '))' && !c.L[0].art){
      const merged = {L:b.L.concat(c.L), w:'s', kind:'CL', cluster:true};
      const one = syl.slice(0, n-2).concat([merged]);
      const none = syl.slice(0, n-2);
      out.length = 0;
      out.push({syl:one, dec:[{id:'F4.2-final-cluster', opt:'one-short'}]});
      out.push({syl, dec:[{id:'F4.2-final-cluster', opt:'two-shorts'}]});
      if(none.length) out.push({syl:none, dec:[{id:'F4.2-final-cluster', opt:'silent'}]});
    }
  }
  /* 4.3: word-initial consonant + consonant (mostly y) + vowel scanned as one onset */
  const res = [];
  for(const o of out){
    const s0 = o.syl[0], s1 = o.syl[1];
    if(s0 && s1 && s0.kind === 'C0' && ['CV','CC','CH'].includes(s1.kind) && s1.L[0].k === 'C' && s1.L[0].s !== '))' && s0.L[0].s !== '))'){
      const key = s1.L[0].s === 'y' ? 'y' : 'other';
      const merged = Object.assign({}, s1, {L:s0.L.concat(s1.L), conj3:true});
      res.push({syl:[merged].concat(o.syl.slice(2)), dec:o.dec.concat([{id:'F4.3-initial-conjunct', opt:'conjunct', key}])});
      res.push({syl:o.syl, dec:o.dec.concat([{id:'F4.3-initial-conjunct', opt:'separate', key}])});
    } else res.push(o);
  }
  return res;
}

/* ---------- flexibility marking (2.1, 2.2, 3.2, 3.3) ---------- */
function markFlex(syl, word, ctx){
  const n = syl.length;
  syl.forEach(s => { s.flex = null; });
  for(const s of syl){
    const suf = s.L.find(x => x.iz || x.conj);
    if(suf){
      const id = suf.iz ? 'F3.2-weight' : 'F3.3-weight';
      const key = suf.alone ? 'after-' + (suf.afterLong || 'other') : 'joined';
      s.w = 'x'; s.flex = {id, key}; s.iz = !!suf.iz; s.conj = !!suf.conj;
    }
  }
  /* 3.3: h read as a vowel before an independent o -> that syllable is a 2.2 final CH */
  for(let k = 1; k < n; k++){
    const s = syl[k], p = syl[k-1];
    if(s.conj && s.L[0].afterLong === 'h' && p.L.length === 2 && p.L[1].s === 'h'){ p.w = 'x'; p.flex = {id:'F2.2-final-ii-e-h', key:'h', word}; }
  }
  const med = LEX.medial_flexible[word];
  if(med) med.forEach(k => { if(syl[k] && !syl[k].flex){ syl[k].w = 'x'; syl[k].flex = {id:'F2.2-medial-lexical', key:word, word}; } });
  if(ctx.suffixed || ctx.article){ hamzaFlex(syl, word); return; }
  const last = syl[n-1];
  const lex = LEX.monosyllables[word];
  if(n === 1){
    if(lex){ last.w = lex.w; if(lex.w === 'x') last.flex = {id: lex.rule, key: lex.cls, word}; return; }
    if(last.kind === 'CV' || last.kind === 'CH' || (last.kind === 'AV')){
      last.w = 'x'; last.flex = {id:'F2.1-other-monosyllable', key: vowelKey(last), word}; return;
    }
    return;
  }
  if(last.kind === 'CV' || last.kind === 'CH'){
    last.w = 'x'; last.flex = {id: finalRule(last), key: vowelKey(last) + (ctx.origin !== 'unknown' && !['ii','e','h'].includes(vowelKey(last)) ? ':' + ctx.origin : ''), word};
  }
  hamzaFlex(syl, word);
}
function hamzaFlex(syl, word){
  const n = syl.length;
  /* 2.2 grammatical forms: future jaa))egaa (= x x); plurals aa;Nsuu))o;N (= x x) */
  for(let k = 1; k < n; k++){
    const s = syl[k], p = syl[k-1];
    const hamzaV = s.kind === 'CV' && s.L[0].s === '))' && k < n-1 && syl[k+1].L[0].s === 'g';
    if(hamzaV){ s.w = 'x'; s.flex = {id:'F2.2-future', key:'))' + s.L[1].s, word}; }
    /* 2.2: flexibility remains in -uu (and -o) before a final hamza + vowel ending:
       aa;Nsuu))o;N (= x x), juu))e;N (x x), ko))ii (x x); glossary duu))ii (x x), muu))e (- x) */
    if(!DISABLED.has('F2.2-before-hamza') && k === n-1 && s.kind === 'CV' && s.L[0].s === '))' && p.kind === 'CV' && p.L.length === 2 && (p.L[1].s === 'uu' || p.L[1].s === 'o') && !p.flex){
      p.w = 'x'; p.flex = {id:'F2.2-before-hamza', key:p.L[1].s, word};
    }
  }
}
function vowelKey(s){
  const x = s.L[s.L.length-1];
  if(s.kind === 'CH') return 'h';
  const v = x.s; const b = VAO.has(v) ? 'o' : (v === 'ai' ? 'e' : v);
  return b + (x.nas ? ';N' : '');
}
function finalRule(s){
  const k = vowelKey(s).replace(';N','');
  return (k === 'ii' || k === 'e' || k === 'h') ? 'F2.2-final-ii-e-h' : 'F2.2-final-o-aa';
}

/* ---------- a word (or grafted chain) -> readings ---------- */
function wordReadings(w){
  /* w: {word, items, iz, conjO, article, origin} */
  const out = [];
  const bare = !w.iz && !w.conjO && !w.article;
  const alt = bare ? (LEX.alternate_splits[w.word] || GLEX[w.word] || null) : null;
  const base = lexicalItemAlts(w.word, w.items);
  if(alt) base.forEach(b => b.dec = b.dec.concat([{id:alt[0].rule, opt:'regular', key:w.word}]));
  for(const b of base){
    let variants = [{items:b.items, dec:b.dec}];
    const suffixKinds = [w.iz && 'iz', w.conjO && 'o', w.article && 'al'].filter(Boolean);
    for(const kind of suffixKinds){
      const nv = [];
      variants.forEach(v => applySuffix(v.items, kind, w).forEach(r => nv.push({items:r.items, dec:v.dec.concat(r.dec)})));
      variants = nv;
    }
    for(const v of variants){
      const L = toLetters(v.items);
      const syl0 = syllabify(L);
      for(const ca of clusterAlts(syl0, suffixKinds.length > 0)){
        const syl = ca.syl.map(s => Object.assign({}, s));
        markFlex(syl, w.word, {suffixed: suffixKinds.length > 0, article: !!w.article, origin: w.origin});
        if(b.aurSingle && !suffixKinds.length){ const l = syl[syl.length-1]; l.w = 'x'; l.flex = {id:'F2.1-aur-weight', key:'single', word:'aur'}; }
        const dec = v.dec.concat(ca.dec);
        out.push(finishReading(syl, dec, w));
      }
    }
  }
  /* 2.3 alternate splits / special scansions given as whole patterns in the lexicon */
  if(alt) alt.forEach(a => out.push(patternReading(a.pattern, a.split, [{id:a.rule, opt:a.opt, key:w.word}], w, a.flex)));
  return dedupe(out);
}
function patternReading(pattern, split, dec, w, flexRule){
  const parts = split.split('-');
  const syl = pattern.split(' ').map((c, k) => ({w: c === '=' ? 'l' : c === '-' ? 's' : 'x', text: parts[k] || '?', L:[], kind:'LEX',
    flex: c === 'x' ? {id: flexRule || 'F2.2-final-ii-e-h', key: flexRule ? 'single' : 'lex', word:w.word} : null}));
  return finishReading(syl, dec, w);
}
function finishReading(syl, dec, w){
  const S = syl.map((s, k) => ({
    w: s.w, text: s.text || sylText(s), flex: s.flex || null, iz: !!s.iz, conj: !!s.conj,
    n: s.L.length, kind: s.kind,
    cheat: k === syl.length-1 && !s.iz && !s.conj && ((s.w === 's' && (s.L.length === 1 || s.cluster)) || (s.L.length === 2 && s.L[0].s === '))'))
  }));
  /* 7 / 3.2: three shorts never occur in a row -- a flexible caught between two shorts
     can only be long; three definite shorts make the reading impossible */
  let run = 0; for(const s of S){ run = s.w === 's' ? run + 1 : 0; if(run >= 3) return null; }
  let c = 0; for(const d of dec) c += cost(P.choice(d.id, d.opt, d.key));
  return {syl:S, dec, cost:c};
}
function dedupe(rs){
  const seen = new Map();
  for(const r of rs){ if(!r || r.cost === Infinity) continue;
    const k = r.syl.map(s => s.w + (s.flex ? s.flex.id + s.flex.key : '') + (s.cheat ? 'c' : '')).join('.');
    const o = seen.get(k); if(!o || r.cost < o.cost) seen.set(k, r); }
  return [...seen.values()].sort((a, b) => a.cost - b.cost);
}

/* ---------- grafting (3.1): join a chain of words into one item string ---------- */
function graftCheck(a, b){
  /* a ends in a consonant letter, b begins with alif / alif madd. Returns rule id or null */
  if(!a || !b || a.iz || a.conjO || a.article) return null;
  const j = lastLetterIdx(a.items); if(j < 0) return null;
  const last = a.items[j];
  const first = b.items[0];
  if(!first) return null;
  if(last.k === 'C'){
    if(first.k === 'A' || first.k === 'AA') return last.s === 'h' && a.items.slice(j+1).length === 0 && a.items[j-1] && a.items[j-1].k === 'v' ? 'F3.1-graft-h' : 'F3.1-graft';
    if(first.k === 'C' && first.s === '((') return 'F3.1-graft-ain';
    return null;
  }
  if(last.k === 'V' && (first.k === 'A' || first.k === 'AA') && ['ii','e','o','uu'].includes(last.s)) return 'F3.1-graft-vowel';
  return null;
}
function graftItems(a, b, rule){
  let left = a.items.slice();
  if(rule === 'F3.1-graft-vowel'){
    const j = lastLetterIdx(left), v = left[j].s;
    left = left.slice(0, j).concat([{k:'v', s: v === 'ii' || v === 'e' ? 'i' : 'u'}, {k:'C', s: v === 'ii' || v === 'e' ? 'y' : 'v'}]);
  }
  let right = b.items.slice();
  const f = right[0];
  if(f.k === 'AA') right = [{k:'V', s:'aa'}].concat(right.slice(1));
  else if(f.k === 'A' && f.v) right = [{k:'v', s:f.v}].concat(right.slice(1));
  else if(f.k === 'A') right = right.slice(1);
  else if(f.k === 'C' && f.s === '((') right = right.slice(1);
  /* the joint consonant loses any sukun: drop a trailing short-vowel marker already on the left */
  return left.concat(right);
}

module.exports = { disable, toLetters, syllabify, wordReadings, graftCheck, graftItems, setParams, cost, sylText, applySuffix, markFlex, LONGV };
