import json, os

bibliography_data = {
    "metadata": {
        "title": "Comprehensive Bibliography & Attribution Module for Urdu Prosody and Meter",
        "subtitle": "Scholarly credits, classical treatises, lexicons, and oral traditions underlying the Urdu Bahr Handbook & Rhythm Studio",
        "compiled_by": "Urdu Bahr Studio Project",
        "edition": "2026 Interactive Digital Edition",
        "primary_sources_credited": [
            "Frances W. Pritchett & Khawaja Ahmad Khaliq Anjum (Urdu Meter: A Practical Handbook)",
            "A. Sean Pue (AST Graph Transliteration Engine: ghalib.js)",
            "Muhammad Abd-al-Rahman Barker & Shah Abdus Salam (Classical Urdu Poetry)",
            "Frances W. Pritchett (A Desertful of Roses: The Divan of Ghalib)",
            "Shamsur Rahman Faruqi ('Aruz, Aahang aur Bayaan & Dars-e Balaghat)"
        ],
        "categories_count": 6
    },
    "categories": [
        {
            "id": "primary_foundations",
            "name": "Foundational Sources & Direct Engine Credits",
            "urdu_name": "بنیادی مآخذ اور براہ راست محرکات",
            "description": "The direct intellectual, algorithmic, and textual foundations upon which this handbook and interactive studio are built.",
            "entries": [
                {
                    "id": "pritchett_khaliq_1987",
                    "category": "primary_foundations",
                    "category_name": "Foundational Sources & Direct Engine Credits",
                    "authors": ["Frances W. Pritchett", "Khawaja Ahmad Khaliq Anjum"],
                    "title": "Urdu Meter: A Practical Handbook",
                    "urdu_title": "اردو بحور: ایک عملی دستی کتاب",
                    "year": "1987 (Print); 2003+ (Web Edition)",
                    "publisher_or_affiliation": "South Asian Studies, University of Wisconsin-Madison (1987); Middle Eastern, South Asian, and African Studies (MESAAS), Columbia University (Web Edition)",
                    "canonical_url": "https://www.franpritchett.com/00ghalib/meterbk/00_intro.html",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "Designed as a descriptive, accessible, code-breaking pedagogy for students and lovers of Urdu poetry, bypassing intimidating classical Arabic taxonomy in favor of empirical syllable weight rules.",
                    "significance_note": "The primary theoretical and pedagogical cornerstone of this application. Pritchett & Khaliq introduced the revolutionary empirical rule: '2 letters = Long (=), 1 letter = Short (-)', the code-breaking vertical alignment ('stacking') method, the catalog of 37 classical meters grouped into 7 recognizable melodic families, the precise rules of flexibility (x) and word-grafting (vas̤l), and 24 canonical ghazal exercises with answer keys. This entire application implements and extends their methodology into a live digital environment."
                },
                {
                    "id": "pue_ast_transliteration",
                    "authors": ["A. Sean Pue"],
                    "category": "primary_foundations",
                    "category_name": "Foundational Sources & Direct Engine Credits",
                    "title": "Finite-State AST Graph Transliteration & Multi-Script Parsing Engine (ghalib.js)",
                    "urdu_title": "محدود المعطیات گراف پر مبنی کثیر الخطی ٹرانسلٹریشن انجن",
                    "year": "2002–present",
                    "publisher_or_affiliation": "Department of Linguistics, Languages, and Cultures, Michigan State University; Columbia University South Asian Digital Humanities",
                    "canonical_url": "https://www.columbia.edu/itc/mealac/pritchett/00ghalib/script/ghalib.js",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "Installed in October 2002 on Columbia's A Desertful of Roses: The Divan of Ghalib. Frances Pritchett credits Sean Pue with providing the intellectual 'spark' to create the Ghalib web database and developing the script-bar program enabling instantaneous switching between Urdu, Devanagari, and Roman diacritics.",
                    "significance_note": "Developer of the underlying graph AST parser ('ghalib.js') and transition matrices ('urdu_parser_data.js', 'devanagari_parser_data.js', 'diacritics_parser_data.js') included in 'pritchett_scripts/'. This engine operates as a deterministic finite-state transducer across an abstract syntax tree of Urdu phonemes, handling contextual hamzah insertion, iz̤āfat suffixes, nūn-e ghunnah, and compound vowels. In this studio, Sean Pue's algorithm powers our multi-script toggle (Urdu Nastaliq, Devanagari, and Roman diacritics), enabling seamless cross-script recitation and auditory drills."
                },
                {
                    "id": "barker_salam_1977",
                    "authors": ["Muhammad Abd-al-Rahman Barker", "Shah Abdus Salam"],
                    "category": "primary_foundations",
                    "category_name": "Foundational Sources & Direct Engine Credits",
                    "title": "Classical Urdu Poetry (3 vols.)",
                    "urdu_title": "کلاسیکی اردو شاعری (تین جلدیں)",
                    "year": "1977",
                    "publisher_or_affiliation": "Spoken Language Services, Inc., Ithaca, N.Y.",
                    "canonical_url": "https://dsal.uchicago.edu/books/barker/",
                    "in_original_ch9": True,
                    "ch9_anchor": "barker",
                    "pritchett_note": "Volume I contains: Appendix I: Urdu Poetics-- A.130 Scansion (pp. xxxv-xl); A.140 Measure and Metre (pp. xl-xlvi); A.150 Catalexis (pp. xlvi-lxiv). An account which touches on all major points of metrical theory with accuracy and technical sophistication. Excellent reference work for students.",
                    "significance_note": "The definitive source anthology from which the 24 canonical exercise ghazals (spanning Wali, Dard, Mir, Sauda, Mushafi, Insha, Jur'at, Atish, Nasikh, Momin, Zafar, Ghalib, Zauq, Dagh, and Iqbal) in Chapter 10 of the handbook were curated. Barker & Salam's rigorous phonological notations (CVC/CV syllable modeling) established the structural gold standard for western academic Urdu linguistic pedagogy."
                },
                {
                    "id": "pritchett_desertful_roses",
                    "authors": ["Frances W. Pritchett"],
                    "category": "primary_foundations",
                    "category_name": "Foundational Sources & Direct Engine Credits",
                    "title": "A Desertful of Roses: The Divan of Ghalib",
                    "urdu_title": "صحراے گل: دیوانِ غالب کا مکمل تشریحی منصوبہ",
                    "year": "2000–present",
                    "publisher_or_affiliation": "Columbia University Digital Humanities / Middle Eastern, South Asian, and African Studies",
                    "canonical_url": "https://www.franpritchett.com/00ghalib/",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "A comprehensive digital commentary on every sher of Ghalib's Urdu Divan, featuring complete scansions, verse-by-verse metrical tags, classical commentaries (Nazm, Tabataba'i, Bekhud, Asi), and English translations.",
                    "significance_note": "The largest digital repository of verified Urdu scansions and metrical tags in the world. Pritchett's metrical annotations across Ghalib's 234 ghazals provide the empirical corpus against which our scansion engine was validated. The companion project 'A Garden of Kashmir' (on Mir Taqi Mir's divan) provides further empirical validation for irregular and Hindi-derived meters."
                }
            ]
        },
        {
            "id": "classical_treatises_urdu",
            "name": "Classical & Contemporary Urdu Treatises",
            "urdu_name": "کلاسیکی اور معاصر اردو رسائل و تالیفات",
            "description": "Authoritative historical and modern Urdu-language treatises on ‘Ilm-e-‘Arūz, rhetoric (Balāghat), and poetic practice.",
            "entries": [
                {
                    "id": "faruqi_aruz_1977",
                    "authors": ["Shamsur Rahman Faruqi"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "‘Arūz, Āhang aur Bayān",
                    "urdu_title": "عروض، آہنگ اور بیان",
                    "year": "1977",
                    "publisher_or_affiliation": "Kitab Nagar, Lucknow (258 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/arooz-aahang-aur-bayan-shamsur-rahman-faruqi-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": "aruz",
                    "pritchett_note": "Thoughtful and original discussions of some problematical aspects of Urdu meter, by a critic versed in both Urdu and English poetic theory. The essays are difficult, but highly rewarding.",
                    "significance_note": "The preeminent modern theoretical critique of Urdu prosody. Faruqi revolutionized the field by demonstrating that Urdu meter is grounded in an auditory-temporal pulse (āhang) distinct from rigid Arabic quantitative syllabics. His extensive notes provided the intellectual foundation for Pritchett & Khaliq's treatment of compound meters and medial pause (taskīn-e ausaṭ)."
                },
                {
                    "id": "faruqi_dars_1981",
                    "authors": ["Shamsur Rahman Faruqi (ed.)"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Dars-e Balāghat",
                    "urdu_title": "درسِ بلاغت",
                    "year": "1981",
                    "publisher_or_affiliation": "Bureau for the Promotion of Urdu, Government of India, New Delhi (192 p.)",
                    "canonical_url": "https://www.franpritchett.com/00urduhindilinks/darsebalaghat/darsebalaghat.html",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A primer on meter designed for undergraduates; very simply written, accurate, and avoids controversial issues. Explains scansion and other metrical points with great clarity.",
                    "significance_note": "The standard university textbook across South Asia for teaching Urdu rhetorical figures (ṣanāyi‘-o-badāyi‘) and basic prosody. It serves as an accessible pedagogical bridge between classical Arabic terminology and modern literary education."
                },
                {
                    "id": "auj_miqyas_1886",
                    "authors": ["Mirza Muhammad Ja'far Auj"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Miqyās ul-Ash‘ār",
                    "urdu_title": "مقیاس الاشعار",
                    "year": "1886",
                    "publisher_or_affiliation": "Matba‘-e Ja‘fari, Lucknow (336 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/miqyas-ul-ashaar-mirza-mohammad-jafar-auj-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "The most exhaustive, authoritative, and painstaking of the classical works on Urdu meter.",
                    "significance_note": "Regarded by classical ustāds as the supreme manual of Urdu prosodic theory. Auj, son of the celebrated elegist Mir Munis and descendant of Mir Anis, brought consummate Lucknow courtly rigor to classifying all permutations, rare variations, and permissible licenses in Urdu poetry."
                },
                {
                    "id": "najm_bahr_1885",
                    "authors": ["Najm ul-Ghani Rampuri"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Baḥr ul-Faṣāḥat",
                    "urdu_title": "بحر الفصاحت",
                    "year": "1885 (1st ed.); 1926 (2nd ed.); 1927 (3rd ed.)",
                    "publisher_or_affiliation": "Naval Kishor Press, Lucknow (1232 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/bahr-ul-fasahat-volume-001-najmul-ghani-rampoori-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "This voluminous work on Urdu poetics contains one sizable chapter, perhaps a couple hundred pages, on meter. It is more commonly used as a reference today than any other work of its kind.",
                    "significance_note": "The monumental encyclopedia of Urdu rhetoric, prosody, rhyme, and grammatical idiom from the late 19th-century Rampur and Lucknow traditions. Its exhaustive chapter on ‘Arūz remains the standard historical point of reference for classical poetics."
                },
                {
                    "id": "badr_sihhat_1977",
                    "authors": ["Sayyid Badr ul-Hasan"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Ṣiḥḥat-e Alfāẓ",
                    "urdu_title": "صحتِ الفاظ",
                    "year": "1977",
                    "publisher_or_affiliation": "Kutubkhanah Anjuman Taraqqi-e Urdu, Delhi (119 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/sehat-ul-alfaaz-syed-badrul-hasan-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": "sihhat",
                    "pritchett_note": "The whole book consists of a series of lists of Urdu words that are difficult or problematical for various reasons. Clearly laid out and contains an alphabetical index.",
                    "significance_note": "Crucial guide for orthographic and vocalic correctness in classical poetry. Badr ul-Hasan catalogs common pronunciation pitfalls, disputed short vowels (zer/zabar/pesh), Arabic broken plurals, and Persian compound pronunciations that directly affect syllable weights in scansion."
                },
                {
                    "id": "saghir_ghazaliyat_1984",
                    "authors": ["Saghir ul-Nisa Begum"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Ghazaliyāt-e Ghālib kā ‘Arūẓī Tajziyah",
                    "urdu_title": "غزلیاتِ غالب کا عروضی تجزیہ",
                    "year": "1984",
                    "publisher_or_affiliation": "Maktabah Jami‘ah, New Delhi (450 p.)",
                    "canonical_url": "https://www.franpritchett.com/00ghalib/texts/ghazaliyat_ghalib.pdf",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A handbook that explains the traditional metrical system, and then analytically shows the scansion and foot-by-foot breakdown of Ghalib's ghazals. Very convenient for reference.",
                    "significance_note": "A pioneering empirical study that systematically scansion-tested every ghazal in Ghalib's Divan line-by-line, providing foot-by-foot arkān breakdowns. A vital corroborating benchmark for our algorithmic meter solver."
                },
                {
                    "id": "asir_zar_1903",
                    "authors": ["Muzaffar Ali Asir"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Zar-e Kāmil ‘Ayār",
                    "urdu_title": "زرِ کامل عیار",
                    "year": "1903 (2nd ed.)",
                    "publisher_or_affiliation": "Naval Kishor Press, Lucknow (308 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/zar-e-kamil-aiyar-muzaffar-ali-aseer-lakhnavi-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A translation of the famous Persian treatise Mi‘yār ul-Ash‘ār, attributed to Nasir al-Din Tusi (d. 1274). The original work, without its numerous examples, was only about 50 pages long; Asir's work is a full-fledged manual in Urdu.",
                    "significance_note": "Historically links classical Urdu prosody directly to Nasir al-Din al-Tusi's 13th-century foundational Persian system, adapting medieval Greco-Arabic rhythmic theories for late 19th-century Urdu literary pedagogy."
                },
                {
                    "id": "faqir_hadaik_1915",
                    "authors": ["Shamsuddin Faqir", "Imam Bakhsh Sahba'i (trans.)"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Ḥadā’iq ul-Balāghat",
                    "urdu_title": "حدائق البلاغت",
                    "year": "1768 (Persian original); 1842 (Urdu trans.); 1915",
                    "publisher_or_affiliation": "Naval Kishor Press, Kanpur (192 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/hadaiq-ul-balaghat-mir-shamsuddin-faqeer-dehlavi-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Composed in Persian in 1768, translated into Urdu in 1842 by Imam Bakhsh Sahba'i of Delhi College, who replaced the Persian examples with Urdu ones. A very famous and influential work.",
                    "significance_note": "Represents the intellectual zenith of Delhi College's early 19th-century literary renaissance before 1857. Sahba'i's translation adapted the Persian rhetorical garden for the Delhi school of poets, including Ghalib and Zauq."
                },
                {
                    "id": "yaganah_chiragh_1914",
                    "authors": ["Mirza Yas Yaganah Changezi"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Chirāgh-e Sukhan",
                    "urdu_title": "چراغِ سخن",
                    "year": "1914 / 1927",
                    "publisher_or_affiliation": "Siddiq Book Depot, Lucknow (c. 144 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/chiragh-e-sukhan-mirza-yagana-changezi-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Notable for listing ALL variants, even the rarest and oddest, of the Urdu meters, in an attempt to be exhaustive. Can be consulted when rare variations are encountered.",
                    "significance_note": "Yaganah's fiery iconoclasm shines through in this unvarnished inventory of extreme metrical anomalies, catalexis forms, and rare rhythmic permutations that orthodox manuals often omitted."
                },
                {
                    "id": "azad_abehayat_1880",
                    "authors": ["Muhammad Husain Azad"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Āb-e Ḥayāt",
                    "urdu_title": "آبِ حیات: تاریخِ شعراے اردو",
                    "year": "1880 (1st ed.); English trans. by Frances W. Pritchett & Shamsur Rahman Faruqi, 2001",
                    "publisher_or_affiliation": "Victoria Press, Lahore (1880); Oxford University Press (2001)",
                    "canonical_url": "https://www.franpritchett.com/00urduhindilinks/abehayat/abehayat.html",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "The foundational biographical and critical history of Urdu poetry, shaping the canon into five historical epochs and establishing the cultural mythology of the classical ustāds.",
                    "significance_note": "Provides the essential historical, biographical, and anecdotal context for the poets featured in our 24 exercise ghazals (Wali, Dard, Mir, Sauda, Ghalib, Zauq, etc.). Azad's critical anecdotes illustrate how meter was treated as an unbendable prerequisite of poetic nobility."
                },
                {
                    "id": "safir_bilgrami_1844",
                    "authors": ["Safir Bilgrami"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Qawā‘id ul-‘Arūẓ",
                    "urdu_title": "قواعد العروض",
                    "year": "c. 1844",
                    "publisher_or_affiliation": "Manuscript / Classical Lithograph, Lucknow",
                    "canonical_url": "https://rekhta.org/ebooks/qawaid-ul-urooz-safeer-bilgrami-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Safir Bilgrami was a shagird of Ghalib's; this book is considered quite authoritative.",
                    "significance_note": "Presents direct insider insight into the mid-19th century teaching methods and prosodic doctrines transmitted directly by Ghalib and the Delhi poetic circle."
                },
                {
                    "id": "allami_kilid_1981",
                    "authors": ["Zar ‘Allami"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Kilīd-e ‘Arūẓ",
                    "urdu_title": "کلیدِ عروض",
                    "year": "1981",
                    "publisher_or_affiliation": "Patiala / Shama‘-e Khayal, Saharanpur (208 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/kaleed-e-urooz-zar-allami-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "The author is a well-known prosodist of the old school; his ustad in prosody was the famous Seemab Akbarabadi.",
                    "significance_note": "Transmits the rigorous prosodic lineage of the Agra/Seemab Akbarabadi school into late 20th-century Indian Urdu literary practice."
                },
                {
                    "id": "wahid_ahang_1978",
                    "authors": ["Abu Zafar Abdul Wahid"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "Āhang-e Shi‘r",
                    "urdu_title": "آہنگِ شعر",
                    "year": "1978",
                    "publisher_or_affiliation": "Andhra Pradesh Urdu Academy, Hyderabad",
                    "canonical_url": "https://rekhta.org/ebooks/aahang-e-sher-abu-zafar-abdul-wahid-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Discusses meter and rhyme in great detail, making reference to the Hindi Pingal system as well.",
                    "significance_note": "One of the few Urdu-language treatises to explicitly compare Arabic-Persian quantitative meter with the mātrā-based moraic Pingal system of Hindi/Sanskrit, reflecting the Deccan's syncretic prosodic heritage."
                },
                {
                    "id": "ilahabadi_ilm_1974",
                    "authors": ["Hasan Kazim ‘Aruz Ilahabadi"],
                    "category": "classical_treatises_urdu",
                    "category_name": "Classical & Contemporary Urdu Treatises",
                    "title": "‘Ilm-e ‘Arūẓ o Qāfiyah o Tārīkh Go’ī",
                    "urdu_title": "علمِ عروض و قافیہ و تاریخ گوئی",
                    "year": "1974",
                    "publisher_or_affiliation": "By the author, Allahabad (96 p.)",
                    "canonical_url": "https://rekhta.org/ebooks/ilm-e-urooz-o-qafiya-wa-tareekh-goi-hasan-kazim-arooz-allahabadi-ebooks",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A small volume, generally accurate and very handy for quick reference on meter, rhyme, and chronograms (tarikh).",
                    "significance_note": "Compact field handbook for poets seeking quick references for rhyme constraints (qāfiyah/radīf) and chronogrammatic numerology (abjad/tārīkh-go’ī)."
                }
            ]
        },
        {
            "id": "western_and_comparative_scholarship",
            "name": "Western & Comparative Prosodic Scholarship",
            "urdu_name": "مغربی اور تقابلی عروضی تحقیقات",
            "description": "Scholarly analyses of Urdu meter produced in Western academia, comparing Perso-Arabic metrics with English stress, Hindi Pingal, and generative phonology.",
            "entries": [
                {
                    "id": "bailey_guide_1937",
                    "authors": ["T. Grahame Bailey"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "A Guide to the Metres of Urdu Verse",
                    "urdu_title": "اردو بحور کی رہنمائی",
                    "year": "1937–1939",
                    "publisher_or_affiliation": "Bulletin of the School of Oriental and African Studies (BSOAS), Vol. 9, No. 4, pp. 969–985",
                    "canonical_url": "https://www.jstor.org/stable/608226",
                    "in_original_ch9": True,
                    "ch9_anchor": "bailey",
                    "pritchett_note": "Contains an exhaustive and well-organized list of meters, giving long and short syllables together with afa'il in transliteration and basic one-word meter names. Gives a short list of common meters convenient for quick reference.",
                    "significance_note": "The first systematic catalog of Urdu meters published in an English academic journal. Bailey mapped classical afā‘īl to long/short symbols (= / -), creating the foundation upon which Russell, Barker, and Pritchett built their classifications."
                },
                {
                    "id": "russell_primer_1974",
                    "authors": ["Ralph Russell"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "A Primer of Urdu Verse Metre",
                    "urdu_title": "ابتدائی اردو عروض",
                    "year": "1974",
                    "publisher_or_affiliation": "By the author, London (Mimeographed and ringbound)",
                    "canonical_url": "https://www.franpritchett.com/00ghalib/meterbk/09_bib.html#russell_primer",
                    "in_original_ch9": True,
                    "ch9_anchor": "russell_primer",
                    "pritchett_note": "Contains Russell's views on the nature of Urdu meter, in a simplified form appropriate to students just beginning study.",
                    "significance_note": "Pioneered the musical and pedagogical reduction of complex Arabic feet into simple mnemonic duration patterns, demonstrating that English-speaking students can master Urdu meter without years of Arabic grammar."
                },
                {
                    "id": "russell_problems_1960",
                    "authors": ["Ralph Russell"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "Some Problems of the Treatment of Urdu Metre",
                    "urdu_title": "اردو عروض کے چند مسائل",
                    "year": "1960",
                    "publisher_or_affiliation": "Journal of the Royal Asiatic Society (JRAS), Apr. 1960, pp. 48–58",
                    "canonical_url": "https://www.jstor.org/stable/25202322",
                    "in_original_ch9": True,
                    "ch9_anchor": "russell_problems",
                    "pritchett_note": "Begins with a discussion of the difficulties of traditional scansion, and proceeds to a critique of Grahame Bailey's approach. Argues for treating Urdu meter in terms of musical bars or measures.",
                    "significance_note": "Seminal essay proposing that Urdu meter is fundamentally isochronous and musical, challenging the rigid grammatical orthodoxy of traditional treatises."
                },
                {
                    "id": "russell_islam_three_mughal_1968",
                    "authors": ["Ralph Russell", "Khurshidul Islam"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "Three Mughal Poets: Mir, Sauda, Mir Hasan",
                    "urdu_title": "تین مغل شعرا: میر، سودا، میر حسن",
                    "year": "1968",
                    "publisher_or_affiliation": "Harvard University Press, Cambridge, Mass.",
                    "canonical_url": "https://www.hup.harvard.edu/books/9780674889804",
                    "in_original_ch9": True,
                    "ch9_anchor": "russell_islam",
                    "pritchett_note": "Contains an Appendix: 'A Complete Ghazal of Mir' (pp. 271-277), offering an account of Mir's 'Hindi' meter that is very useful and suggestive.",
                    "significance_note": "The definitive analysis in English of Mir Taqi Mir's indigenous Hindi moraic meters, directly inspiring Pritchett's treatment of Hindi meters in Chapter 6."
                },
                {
                    "id": "pybus_textbook_1924",
                    "authors": ["Captain G. D. Pybus"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "A Textbook of Urdu Prosody and Rhetoric",
                    "urdu_title": "درسی کتاب برائے اردو عروض و بیان",
                    "year": "1924",
                    "publisher_or_affiliation": "Ramakrishna and Sons, Lahore (viii, 151 p.)",
                    "canonical_url": "https://www.franpritchett.com/00urduhindilinks/pybus/pybus.html",
                    "in_original_ch9": True,
                    "ch9_anchor": "pybus",
                    "pritchett_note": "A translation and adaptation of classical Persian/Arabic theory for British colonial civil and military examinations. The official system described is notoriously user-unfriendly.",
                    "significance_note": "Pritchett frequently cites Pybus as the ultimate example of why traditional Arabic prosodic theory repels students, contrasting his convoluted circles (dā’ire) with her pragmatic code-breaking approach."
                },
                {
                    "id": "matthews_shackle_1972",
                    "authors": ["D. J. Matthews", "Christopher Shackle"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "An Anthology of Classical Urdu Love Lyrics: Text and Translations",
                    "urdu_title": "کلاسیکی اردو غزلوں کا مجموعہ",
                    "year": "1972",
                    "publisher_or_affiliation": "Oxford University Press, London (Appendix I: Notes on Prosody and Meter, pp. 210–213)",
                    "canonical_url": "https://academic.oup.com/",
                    "in_original_ch9": True,
                    "ch9_anchor": "matthews_shackle",
                    "pritchett_note": "An extremely condensed account of Urdu meter, basically following Barker, but giving long and short marks instead of C's and V's. Provides a short list of 17 common meters.",
                    "significance_note": "A concise bridge between Barker's linguistic formalism and accessible undergraduate pedagogy, providing a streamlined list of the 17 most frequent meters in the ghazal repertoire."
                },
                {
                    "id": "thiesen_manual_1982",
                    "authors": ["Finn Thiesen"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "A Manual of Classical Persian Prosody; With Chapters on Urdu, Karakhandic and Ottoman Prosody",
                    "urdu_title": "کلاسیکی فارسی عروض کا جامع دستی نسخہ",
                    "year": "1982",
                    "publisher_or_affiliation": "Otto Harrassowitz, Wiesbaden",
                    "canonical_url": "https://www.harrassowitz-verlag.de/",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A detailed and sophisticated account; the author is learned in classical theory and at home with modern linguistic tools.",
                    "significance_note": "Masterwork of comparative Islamic prosody. Situates Urdu's metrical adaptations within the broader Persianate linguistic sphere alongside Ottoman Turkish and Karakhanid Turkic."
                },
                {
                    "id": "elwell_sutton_1976",
                    "authors": ["L. P. Elwell-Sutton"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "The Persian Metres",
                    "urdu_title": "فارسی بحور",
                    "year": "1976",
                    "publisher_or_affiliation": "Cambridge University Press, London (xiv, 285 p.)",
                    "canonical_url": "https://www.cambridge.org/core/books/persian-metres/AEBA16A5ECDCDEFEBFDA07DFE8B4F9A6",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Argues the controversial thesis that Persian meters are not derived from Arabic. Presented with admirable analytic detail.",
                    "significance_note": "Challenged centuries of dogma by arguing that Persian (and by extension Urdu) meters evolved from native accentual-syllabic folk songs rather than Arab quantitative prosody."
                },
                {
                    "id": "blochmann_prosody_1872",
                    "authors": ["Heinrich Ferdinand Blochmann"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "The Prosody of the Persians according to Saifi, Jami, and other writers",
                    "urdu_title": "فارسی عروض: سیفی اور جامی کے تناظر میں",
                    "year": "1872",
                    "publisher_or_affiliation": "Baptist Mission Press, Calcutta",
                    "canonical_url": "https://books.google.com/books?id=2D1bAAAAQAAJ",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A 19th-century classic work explicating Persian prosody from indigenous authorities.",
                    "significance_note": "The primary textbook of Persian prosody across British India for over a century, providing the foundation for 19th-century Indian scholars writing on Urdu."
                },
                {
                    "id": "kiernan_faiz_1971",
                    "authors": ["Victor G. Kiernan (trans. & ed.)"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "Poems by Faiz",
                    "urdu_title": "نقشِ فریادی و دستِ صبا: فیض کے کلام کا منظوم ترجمہ",
                    "year": "1971",
                    "publisher_or_affiliation": "George Allen and Unwin Ltd., London (288 p.)",
                    "canonical_url": "https://www.franpritchett.com/00urdu/3mod/kiernan_faiz/index.html",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A beautiful book containing facing-page calligraphy, reliable transliteration, and poetic translations. Pritchett notes learners must beware of pp. 13-14 where Kiernan mistakenly attempts to impose English stress accent marks onto Urdu quantitative feet.",
                    "significance_note": "Illustrates the fundamental difference between Urdu quantitative meter (duration) and English qualitative meter (stress). Pritchett's critique of Kiernan's preface is a core teaching moment in the handbook."
                },
                {
                    "id": "fairbanks_hindi_1992",
                    "authors": ["Constance Fairbanks"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "Hindi Stress from the Poet's Perspective",
                    "urdu_title": "ہندی تلفظ اور وزن: شاعر کے زاویۂ نظر سے",
                    "year": "1992",
                    "publisher_or_affiliation": "In: Dimensions of Sociolinguistics in South Asia: Papers in Memory of Gerald B. Kelley, ed. E.C. Dimock, B.B. Kachru, Bh. Krishnamurti. Oxford University Press, New Delhi, pp. 297–313",
                    "canonical_url": "https://www.franpritchett.com/00ghalib/texts/txt_fairbanks_hindi_meter_1971.pdf",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Offers an intelligent overview of the metrical structure of modern Hindi poetry, providing illuminating comparisons and contrasts with Urdu.",
                    "significance_note": "Crucial comparative analysis of the phonological overlap between Hindi and Urdu, explaining how identical consonants and vowels function under Pingal mātrā rules versus Perso-Arabic ‘Arūz."
                },
                {
                    "id": "carper_attridge_2003",
                    "authors": ["Thomas Carper", "Derek Attridge"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "Meter and Meaning: An Introduction to Rhythm in Poetry",
                    "urdu_title": "وزن اور معنی: شاعری میں آہنگ کا تعارف",
                    "year": "2003",
                    "publisher_or_affiliation": "Routledge, London (156 p.)",
                    "canonical_url": "https://www.routledge.com/Meter-and-Meaning-An-Introduction-to-Rhythm-in-Poetry/Carper-Attridge/p/book/9780415315791",
                    "in_original_ch9": True,
                    "ch9_anchor": "carper_attridge",
                    "pritchett_note": "I cannot resist including this valuable little work. It does for English meter something like what the present handbook tries to do for Urdu meter.",
                    "significance_note": "Celebrated modern guide to hearing rhythm intuitively rather than mechanically, cited by Frances Pritchett as the conceptual English analogue to her handbook."
                },
                {
                    "id": "smith_poetic_closure_1968",
                    "authors": ["Barbara Herrnstein Smith"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "Poetic Closure: A Study of How Poems End",
                    "urdu_title": "شعری اختتام: نظمیں کیسے مکمل ہوتی ہیں",
                    "year": "1968",
                    "publisher_or_affiliation": "University of Chicago Press, Chicago",
                    "canonical_url": "https://press.uchicago.edu/ucp/books/book/chicago/P/bo3618494.html",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "In terms of ghazal poetics, including meter, this is one of the most revelatory and suggestive works that I've ever found.",
                    "significance_note": "Helps explain the structural dynamics of the classical ghazal: how each two-line sher establishes complete semantic and metrical closure within itself."
                },
                {
                    "id": "loraine_prosody_1973",
                    "authors": ["M. B. Loraine"],
                    "category": "western_and_comparative_scholarship",
                    "category_name": "Western & Comparative Prosodic Scholarship",
                    "title": "Prosody and Rhyme in Classical Arabic and Persian",
                    "urdu_title": "کلاسیکی عربی اور فارسی میں عروض اور قافیہ",
                    "year": "1973",
                    "publisher_or_affiliation": "Unpublished manuscript, University of Washington",
                    "canonical_url": "https://www.franpritchett.com/00ghalib/meterbk/09_bib.html",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "An unpublished academic study analyzing the mechanics of classical Islamic meter and rhyme.",
                    "significance_note": "Reflects the North American South Asian & Middle Eastern academic network in the 1970s that led directly to Barker's and Pritchett's manuals."
                }
            ]
        },
        {
            "id": "lexicons_and_dictionaries",
            "name": "Canonical Lexicons & Dictionaries",
            "urdu_name": "معتبر لغات اور فرہنگیں",
            "description": "The monumental lexicographical authorities defining standard Urdu orthography, vocalization, syllable boundaries, and etymology.",
            "entries": [
                {
                    "id": "platts_dictionary_1884",
                    "authors": ["John T. Platts"],
                    "category": "lexicons_and_dictionaries",
                    "category_name": "Canonical Lexicons & Dictionaries",
                    "title": "A Dictionary of Urdu, Classical Hindi, and English",
                    "urdu_title": "اردو، کلاسیکی ہندی اور انگریزی لغت",
                    "year": "1884 (1st ed.); 1911",
                    "publisher_or_affiliation": "W. H. Allen & Co. / Oxford University Press, London & Oxford",
                    "canonical_url": "https://dsal.uchicago.edu/dictionaries/platts/",
                    "in_original_ch9": True,
                    "ch9_anchor": "platts",
                    "pritchett_note": "While this classic dictionary has nothing directly to do with meter, it's the English-speaking student's best friend, and virtually indispensable for study of the classical ghazal. Gives full vowel markings and marks Persian izafat and Arabic prefixes clearly.",
                    "significance_note": "The indispensable lexicographical foundation for classical Urdu poetry. Platts provides exhaustive diacritics, distinguishes long vowels from short vowels, and documents Sanskrit, Persian, and Arabic etymologies. This is the supreme authority used to verify ambiguous syllable splits and archaic word weights."
                },
                {
                    "id": "steingass_persian_1892",
                    "authors": ["Francis Joseph Steingass"],
                    "category": "lexicons_and_dictionaries",
                    "category_name": "Canonical Lexicons & Dictionaries",
                    "title": "A Comprehensive Persian-English Dictionary, Including the Arabic Words and Phrases to be Met with in Persian Literature",
                    "urdu_title": "جامع فارسی انگریزی لغت",
                    "year": "1892",
                    "publisher_or_affiliation": "Routledge & K. Paul, London",
                    "canonical_url": "https://dsal.uchicago.edu/dictionaries/steingass/",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "The ultimate companion lexicon for Persian and Arabic loanwords, compound constructions, and iz̤āfat phrases encountered throughout classical Urdu ghazals.",
                    "significance_note": "Essential for deciphering classical Persianate compounds, Arabic verbal nouns, and metrical contractions used by Mir, Sauda, Ghalib, and Iqbal. Steingass provides exact classical vocalizations that determine whether a medial syllable is long or short."
                },
                {
                    "id": "udb_tareekhi_lughat",
                    "authors": ["Urdu Dictionary Board (اردو لغت بورڈ)"],
                    "category": "lexicons_and_dictionaries",
                    "category_name": "Canonical Lexicons & Dictionaries",
                    "title": "Urdu Lughat (Tārīkhī Uṣūl Par) — 22 Volumes",
                    "urdu_title": "اردو لغت (تاریخی اصول پر) — بائیس جلدیں",
                    "year": "1958–2010 (Print); Online Edition",
                    "publisher_or_affiliation": "National Language Promotion Department, Government of Pakistan, Karachi",
                    "canonical_url": "http://udb.gov.pk/",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A historical and etymological dictionary project that seeks to be the Oxford English Dictionary of Urdu; formerly in many big volumes, now very conveniently online.",
                    "significance_note": "The ultimate historical authority for Urdu usage across centuries, tracing word origins with verified quotations from classical texts. Crucial for verifying shifting phonology and historical variations in vowel length."
                }
            ]
        },
        {
            "id": "musical_and_oral_traditions",
            "name": "Musical Performance & Oral Traditions",
            "urdu_name": "موسیقی، ترنم اور روایتی گلوکاری",
            "description": "Scholarly works and master performers representing the living auditory tradition of Urdu ghazal singing (Ghazal-sarā’ī) and rhythmic chanting (Tarannum).",
            "entries": [
                {
                    "id": "qureshi_tarannum_1969",
                    "authors": ["Regula Burckhardt Qureshi"],
                    "category": "musical_and_oral_traditions",
                    "category_name": "Musical Performance & Oral Traditions",
                    "title": "Tarannum: The Chanting of Urdu Poetry",
                    "urdu_title": "ترنم: اردو شاعری کا نغماتی آہنگ",
                    "year": "1969",
                    "publisher_or_affiliation": "Ethnomusicology, Vol. 13, No. 3, pp. 425–468",
                    "canonical_url": "https://www.jstor.org/stable/850154",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "The author is a musician herself who sings and plays ghazal beautifully. Much of her work explores how poetic meters relate to musical ones, especially in mushairah recitation.",
                    "significance_note": "The definitive ethnomusicological study of tarannum (the melodic, unaccompanied chant used by poets at mushairahs). Qureshi transcribed tarannum recitations into Western musical notation, showing how quantitative poetic syllables map directly onto musical durations."
                },
                {
                    "id": "qureshi_ghazal_performance_1986",
                    "authors": ["Regula Burckhardt Qureshi"],
                    "category": "musical_and_oral_traditions",
                    "category_name": "Musical Performance & Oral Traditions",
                    "title": "The Urdu Ghazal in Performance",
                    "urdu_title": "اردو غزل کا فنی مظاہرہ",
                    "year": "1986",
                    "publisher_or_affiliation": "In: Urdu and Muslim South Asia: Studies in Honour of Ralph Russell, ed. Christopher Shackle. SOAS, London, pp. 175–189",
                    "canonical_url": "https://www.worldcat.org/title/urdu-and-muslim-south-asia-studies-in-honour-of-ralph-russell/oclc/21295326",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Analyzes the communicative and metrical dynamics between the ghazal singer, the poet, and the participatory audience.",
                    "significance_note": "Explores how the oral delivery of the ghazal creates emotional suspense (tamhīd) by withholding the second rhyming misra until the final cadential beat."
                },
                {
                    "id": "qureshi_sufi_music_1986",
                    "authors": ["Regula Burckhardt Qureshi"],
                    "category": "musical_and_oral_traditions",
                    "category_name": "Musical Performance & Oral Traditions",
                    "title": "Sufi Music of India and Pakistan: Sound and Meaning in the Qawwali",
                    "urdu_title": "ہندوستان اور پاکستان کی صوفی موسیقی: قوالی میں صوت اور معنی",
                    "year": "1986",
                    "publisher_or_affiliation": "Cambridge University Press, Cambridge (xv, 265 p.)",
                    "canonical_url": "https://www.cambridge.org/core/books/sufi-music-of-india-and-pakistan/57257FCE3A19EE2B3E1F9745B74BC9F7",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "A landmark ethnography and musical analysis of how classical Urdu and Persian poetry is performed within Sufi assemblies (samā‘).",
                    "significance_note": "Documents how Qawwali musicians manipulate poetic meter (bahr) against repetitive rhythmic cycles (tāla), maintaining metrical integrity while building ecstatic emotional intensity."
                },
                {
                    "id": "manuel_prosodic_musical_1979",
                    "authors": ["Peter L. Manuel"],
                    "category": "musical_and_oral_traditions",
                    "category_name": "Musical Performance & Oral Traditions",
                    "title": "The Relationship between Prosodic and Musical Rhythms in Urdu Ghazal-Singing",
                    "urdu_title": "اردو غزل گائیکی میں عروضی اور موسیقیائی آہنگ کا باہمی تعلق",
                    "year": "1979 / 1986",
                    "publisher_or_affiliation": "In: Studies in the Urdu Ghazal and Prose Fiction, ed. Muhammad Umar Memon. University of Wisconsin-Madison, pp. 93–119",
                    "canonical_url": "https://www.jstor.org/stable/41699709",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "An interesting and informative article analyzing how semi-classical thumri and dadra talas intersect with poetic meters.",
                    "significance_note": "Provides formal musicological evidence that semi-classical ghazal compositions preserve the quantitative ratios (1:2) of Urdu verse feet when setting lines to North Indian rhythmic cycles like Keharwa, Roopak, and Dadra."
                },
                {
                    "id": "begum_akhtar_tradition",
                    "authors": ["Begum Akhtar (Akhtari Bai Faizabadi)"],
                    "category": "musical_and_oral_traditions",
                    "category_name": "Musical Performance & Oral Traditions",
                    "title": "Mallika-e Ghazal: The Living Tradition of Semi-Classical Ghazal Performance",
                    "urdu_title": "ملکۂ غزل بیگم اختر: کلاسیکی غزل سرائی کی زندہ روایت",
                    "year": "1914–1974; Historic Recordings (HMV / Saregama)",
                    "publisher_or_affiliation": "Lucknow / Faizabad Gharana & All India Radio",
                    "canonical_url": "https://en.wikipedia.org/wiki/Begum_Akhtar",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "The undisputed queen of ghazal singing whose impeccable diction, emotional pathos, and metrical precision set the gold standard for singing Ghalib, Mir, Dagh, and Faiz.",
                    "significance_note": "Begum Akhtar's legendary renditions (such as Ghalib's 'Ibn-e Maryam hu’ā kare ko’ī' and Shakeel's 'Ai mohabbat tere anjām pe ronā āyā') are the supreme artistic embodiment of Urdu meter in performance. Her phrasing respects every quantitative syllable, proving that true musicality flows from the bahr itself."
                },
                {
                    "id": "mehdi_hassan_tradition",
                    "authors": ["Ustad Mehdi Hassan"],
                    "category": "musical_and_oral_traditions",
                    "category_name": "Musical Performance & Oral Traditions",
                    "title": "Shahenshah-e Ghazal: Classical Rāg-Ang Ghazal Recitation & Phrasing",
                    "urdu_title": "شہنشاہِ غزل استاد مہدی حسن: راگ انگ گائیکی اور عروضی نفاست",
                    "year": "1927–2012; Historic Recordings (EMI Pakistan)",
                    "publisher_or_affiliation": "Kalawant Dhrupad Gharana, Rajasthan / Pakistan",
                    "canonical_url": "https://en.wikipedia.org/wiki/Mehdi_Hassan",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "The Shahenshah of Ghazal, whose masterly command of classical ragas and crystal-clear talaffuz (pronunciation) brought Urdu ghazal singing to its highest aesthetic perfection.",
                    "significance_note": "Trained in the rigorous Kalawant Dhrupad tradition, Mehdi Hassan possessed an unerring mathematical ear for the internal pulse of Urdu meters. His renditions of Mir ('Patta patta būṭā būṭā'), Ghalib ('Dil-e-nādāñ tujhe hu’ā kyā hai'), and Faraz ('Ranjish hī sahī') provide the living acoustic templates for our 7 Bahr families."
                }
            ]
        },
        {
            "id": "digital_and_computational_resources",
            "name": "Digital Humanities & Computational Resources",
            "urdu_name": "ڈیجیٹل ہیومینٹیز اور کمپیوٹرائزڈ وسائل",
            "description": "Online platforms, algorithmic prosodic analyzers, and digital repositories dedicated to Urdu literature and prosody.",
            "entries": [
                {
                    "id": "aruuz_com",
                    "authors": ["Sayed Zeeshan"],
                    "category": "digital_and_computational_resources",
                    "category_name": "Digital Humanities & Computational Resources",
                    "title": "Aruuz.com: Automated Urdu Scansion & Metrical Analysis",
                    "urdu_title": "عروض ڈاٹ کام: خودکار اردو تقطیع کا سافٹ ویئر",
                    "year": "2012–present",
                    "publisher_or_affiliation": "Aruuz Software Project",
                    "canonical_url": "http://www.aruuz.com/",
                    "in_original_ch9": True,
                    "ch9_anchor": "9_3",
                    "pritchett_note": "A sophisticated site for scansion and metrical analysis and discussion, maintained by Sayed Zeeshan.",
                    "significance_note": "The foremost web-based computational prosody engine for Urdu. It parses typed Urdu verses and returns candidate meters and foot divisions. A valuable benchmark for algorithmic scansion comparisons."
                },
                {
                    "id": "rekhta_foundation",
                    "authors": ["Rekhta Foundation (Sanjiv Saraf, Founder)"],
                    "category": "digital_and_computational_resources",
                    "category_name": "Digital Humanities & Computational Resources",
                    "title": "Rekhta.org: The World's Largest Repository of Urdu Poetry & Video Lecture Series on ‘Arūz",
                    "urdu_title": "ریختہ فاؤنڈیشن: اردو شاعری کا سب سے بڑا ذخیرہ اور ویڈیوز برائے عروض",
                    "year": "2013–present",
                    "publisher_or_affiliation": "Rekhta Foundation, New Delhi / Noida",
                    "canonical_url": "https://www.rekhta.org/",
                    "in_original_ch9": True,
                    "ch9_anchor": None,
                    "pritchett_note": "Pritchett links in Chapter 9 to Rekhta's video series on the traditional metrical system (25 video lectures by Bhatnagar 'Shadab').",
                    "significance_note": "Rekhta has revolutionized access to Urdu poetry by digitizing hundreds of thousands of ghazals, thousands of classical diwans, and comprehensive audio/video recordings. Their 25-part video lecture series on 'Ilm-e-'Aruz offers an accessible multimedia guide to traditional prosody."
                },
                {
                    "id": "dsal_chicago",
                    "authors": ["Digital South Asia Library (DSAL) & Center for Research Libraries"],
                    "category": "digital_and_computational_resources",
                    "category_name": "Digital Humanities & Computational Resources",
                    "title": "Digital Dictionaries of South Asia (DDSA)",
                    "urdu_title": "جنوبی ایشیا کی ڈیجیٹل لغات (شکاگو یونیورسٹی)",
                    "year": "2000–present",
                    "publisher_or_affiliation": "University of Chicago, Chicago, Illinois",
                    "canonical_url": "https://dsal.uchicago.edu/dictionaries/",
                    "in_original_ch9": False,
                    "ch9_anchor": None,
                    "pritchett_note": "The premier digital humanities project hosting searchable full-text editions of Platts's Urdu-Hindi-English Dictionary, Steingass's Persian-English Dictionary, and Shakespear's Hindustani Dictionary.",
                    "significance_note": "Provides globally accessible, searchable Unicode and scanned facsimiles of the definitive 19th-century colonial lexicons, making instant syllable and etymology verification possible for scholars and students worldwide."
                }
            ]
        }
    ]
}

# Calculate statistics
total_entries = sum(len(c["entries"]) for c in bibliography_data["categories"])
bibliography_data["metadata"]["total_entries_count"] = total_entries

output_path = "data/bibliography.json"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(bibliography_data, f, ensure_ascii=False, indent=2)

print(f"Successfully compiled {total_entries} categorized bibliography entries into {output_path}!")
